import Head from 'next/head'
import Banner from '../components/banner'
import styles from '../styles/Home.module.css'

export default function Home() {
  const handleOnClickBannerBtn = () => {
    console.log('ini di klik boss')
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Coffee Connoiseur</h1>
        <Banner
          buttonText='View store nearby'
          handleOnClick={handleOnClickBannerBtn}
        />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  )
}
